FROM python:3.9

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY /src/ml_endpoint.py /src/ml_endpoint.py
COPY /src/price_prediction.py /src/price_prediction.py

WORKDIR "/src"
# RUN uvicorn ml_endpoint:app --host 0.0.0.0 --port 8000


