FROM python:3.9

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY /src/db_listener.py /src/db_listener.py
COPY /src/db_actions.py /src/db_actions.py
COPY /src/endpoints.py /src/endpoints.py

# Install netcat
RUN apt-get update && \
    apt-get install -y netcat && \
    apt-get clean

COPY wait-for-kafka.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/wait-for-kafka.sh
RUN uvicorn src.endpoints:app --host 0.0.0.0 --port 8000 &


