version: "3.9"
services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile.scraper
    command: ["scrapy", "crawl", "myfancycrawler", "-s", "LOG_LEVEL=INFO", "--nolog", "-s", "JOBDIR=crawls/state"]
    networks:
      - mieszko_kafka-net

  db_service:
    build:
      context: ./db_service
      dockerfile: Dockerfile.consumer
    command: ["python", "/src/db_listener.py"]
    networks:
      - mieszko_kafka-net

networks:
  mieszko_kafka-net:
    external: true
    name: mieszko_kafka-net

