version: "3.9"
services:
  db_service:
    build: ./db_service/
    command: sh -c "sleep 60s ; python3 test.py"
    volumes:
      - './db_service:/db_service'
    ports:
      - '80:8000'
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'offers'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

  rabbitmq:
   image: rabbitmq:3-management-alpine
   container_name: 'rabbitmq'
   ports:
     - 5672:5672
     - 15672:15672
   volumes:
     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
   networks:
     - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge