version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest 
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - mysql
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure
    ports:
      - '9092:9092'
    networks:
      - kafka-net

  mysql:
    image: mysql:latest
    restart: always
    environment:
       MYSQL_DATABASE: 'offers'
       MYSQL_ROOT_PASSWORD: 'root'
    ports:
       - '3306:3306'
    networks:
       - kafka-net

networks:
  kafka-net:
    driver: bridge