version: "3.9"
services:
  db_service:
    build: ./db_service/
    command: sh -c "sleep 60s ; python3 test.py"
    volumes:
      - './db_service:/db_service'
    ports:
      - '80:8000'
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'offers'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'